MySQL_USERNAME=TuanFans
MySQL_PASSWORD=217134
MySQL_DRIVER=com.mysql.cj.jdbc.Driver
MySQL_URL=jdbc:mysql://localhost:3306/mytest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useServerPrepStmts=true&cachePrepStmts=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true